<?php
/**
 * Copyright © 2013-2017 Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<?php
$_productCollection=$this->getLoadedProductCollection();
$_helper = $this->helper('catalog/output');
?>
<?php if(!$_productCollection->count()): ?>
<p class="note-msg"><?php echo $this->__('There are no products matching the selection.') ?></p>
<?php else : ?>
<?php if ($this->getMode()!='grid') : ?>
<?php echo $this->setTemplate('catalog/product/list/list-styles/list-style-01.phtml')->toHtml(); ?>
<?php else: ?>
<?php
$customerSession = Mage::getSingleton('customer/session');
$themeHelper = $this->helper('flexibletheme');
$quickShopHelper = $this->helper('quickviewpro');
$imageHelper = $this->helper('catalog/image');
$labelHelper = $themeHelper->getLabelHelper();
$wishlistHelper = $this->helper('wishlist');
$width = $themeHelper->getConfig('images/category/product_image_width')?:300;
$height = $themeHelper->getConfig('images/category/product_image_height')?:300;
$paddingBottom = $height*100/$width;
$showDescription = $themeHelper->isDisplayOnList('description');
$showSku = $themeHelper->isDisplayOnList('sku');
$showWishlist = $wishlistHelper->isAllow() && $themeHelper->isDisplayOnList('wishlist');
$showCompare = $themeHelper->isDisplayOnList('compare');
$showCart = $themeHelper->isDisplayOnList('addtocart');
$showQuickShop = $themeHelper->isDisplayOnList('quickshop');
$showLabel = $themeHelper->isDisplayOnList('label');
$showThumb = $themeHelper->isDisplayOnList('thumb');
$showName = $themeHelper->isDisplayOnList('name');
$showReview = $themeHelper->isDisplayOnList('review');
$showPrice = $themeHelper->isDisplayOnList('price');
$layout = $themeHelper->getBlockPageLayout($this);
?>
<style type="text/css">
<?= $themeHelper->getColumnStyle('.cdz-products-grid', '.cdz-products-grid .item.product-item', '.product-items .item.product-item', $layout); ?>
</style>

<div class="category-products product-list-style-14">
    <?php echo $this->getToolbarHtml() ?>
    <ul class="cdz-products-grid items product-items flex-grid" data-sameheight=".product-details,.product-item-details">
        <?php foreach ($_productCollection as $_product): ?>
        <?php
        $url = $_product->getProductUrl();
        $name = $this->stripTags($_product->getName(), null, true);
        ?>
        <li class="item product product-item grid-pesquisa">
            <div class="product-item-info">
                <?php if($customerSession->isLoggedIn()) {
                    $is_favorite = Mage::getModel("cistecnologia_listafavoritos/favoritos")->checkFavorite($_product, $customerSession->getId());
                    $listaFavoritos = Mage::getModel("cistecnologia_listafavoritos/favoritos")->getListaFavoritosCollection($customerSession->getId());
                    ?>
                    <div class="wishlist">
                        <button id="btn-adicionar-fav-<?php echo $_product->getId(); ?>" class="adicionado-fav" onclick="addProductFavoritos(<?php echo $_product->getId(); ?>, <?php echo $customerSession->getId(); ?>, this)" <?php echo ($is_favorite)? "" : "style='display: none'" ;?>>
                            <i class="fas fa-heart"></i></button>
                        <button id="btn-remover-fav-<?php echo $_product->getId(); ?>" class="remove-fav btn-favoritos" onclick="abrirOpcoes(<?php echo $_product->getId(); ?>)" <?php echo ($is_favorite)? "style='display: none'" : "" ;?>>
                            <i class="far fa-heart"></i>
                        </button>

                        <!-- <div id="msg-<?php echo $_product->getId(); ?>" style="display: none">Produto adicionado as seus favoritos!</div> -->
                        <div class="box-wish-list" id="mostrar-opcoes-<?php echo $_product->getId(); ?>" style="display: none">
                            <div>
                                <div class="title_wish_list">Selecione a Lista para adicionar o seu favorito</div>
                                <div onclick="fecharJanela(<?php echo $_product->getId(); ?>)"><i class="far fa-times-circle" aria-hidden="true"></i></div>
                                <div class="class_select_wish_list">
                                    <select class="select-lista-favorito" id="select-lista-favorito-<?php echo $_product->getId(); ?>" name="select-lista-favorito-<?php echo $_product->getId(); ?>">
                                        <option value="0">Selecione</option>
                                        <?php foreach ($listaFavoritos as $lista){?>
                                            <option value="<?php echo $lista["lista_favoritos_id"]; ?>"><?php echo $lista["lista_favoritos_nome"]; ?></option>
                                        <?php } ?>
                                    </select>
                                </div>
                            </div>
                            <div>
                                <button class="btn-add-prodcut-list" onclick="addProductFavoritos(<?php echo $_product->getId(); ?>, <?php echo $customerSession->getId(); ?>, this)">Adicionar</button>
                            </div>
                        </div>
                    </div>
                <?php } ?>
                <div class="product-item-top">
                    <a href="<?= $url ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" class="product-image abs-img" style="padding-bottom: <?php echo $paddingBottom ?>%">
                        <img class="product-image-photo main-img" src="<?= $imageHelper->init($_product, 'small_image')->keepFrame(false)->resize($width); ?>" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" />
                        <img class="product-image-photo hovered-img" src="<?= $imageHelper->init($_product, 'thumbnail')->keepFrame(false)->resize($width); ?>" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'thumbnail'), null, true) ?>" id="product-collection-image-<?php echo $_product->getId(); ?>" />
                    </a>
                    <?= $showLabel?$labelHelper->showLabel($_product):''; ?>

                    <?php if ($showCart || $showCompare || $showQuickShop): ?>
                    <div class="button-hover-wrap hidden-xs" style="display: none;">
                        <div class="overlay-bg"></div>
                        <div class="button-panel">
                            <?php if ($showCart) : ?>
                            <?php if(!$_product->canConfigure() && $_product->isSaleable()): ?>
                                <!-- <button type="button" title="<?php echo $this->quoteEscape($this->__('Add to Cart')) ?>" class="button btn-cart" onclick="setLocation('<?php echo $this->getAddToCartUrl($_product) ?>')"><span><span><?php echo $this->__('Add to Cart') ?></span></span></button> -->
                                <button type="button" id="btn-comprar" title="<?php echo $this->quoteEscape($this->__('Add to Cart')) ?>" onclick="setLocation('<?= $url ?>')"  class="button">Comprar</button>
                            <?php elseif($_product->canConfigure() && $_product->isSaleable()): ?>
                                <button type="button" title="<?php echo $this->quoteEscape($this->__('Add to Cart')) ?>" class="button btn-cart" onclick="CodazonAjaxCartPro.getConfigurableOptions('<?php echo $this->getUrl('quickviewpro/cart/view', array('id' => $_product->getId())) ?>')"><span><span><?php echo $this->__('Add to Cart') ?></span></span></button>
                            <?php elseif($_product->getStockItem() && $_product->getStockItem()->getIsInStock()): ?>
                                <a title="<?php echo $this->quoteEscape($this->__('View Details')) ?>" class="button" href="<?php echo $_product->getProductUrl() ?>"><?php echo $this->__('View Details') ?></a>
                            <?php else : ?>
                                <button type="button" title="<?php echo $this->quoteEscape($this->__('Out of stock')) ?>" class="button btn-cart out-of-stock disabled unavailable" disabled><span><span><?php echo $this->__('Out of stock') ?></span></span></button>
                            <?php endif ?>
                            <?php endif; ?>
                            <?= $showQuickShop?$quickShopHelper->getQuickShopButton($_product):''; ?>
                            <?php if(($_compareUrl = $this->getAddToCompareUrl($_product)) && $showCompare): ?>
                            <a href="<?php echo $_compareUrl ?>" class="tocompare link-compare"><?php echo $this->__('Add to Compare') ?></a>
                            <?php endif; ?>

                        </div>
                    </div>
                    <?php endif ?>
                </div>
                <div class="product details product-item-details product-info">
                    <div class="detail-items-wrap">
                        <?php if ($showWishlist) : ?>
                        <div class="product-item-header">
                            <a href="#" class="product-item-brand">Clothing</a>
                            <a href="<?php echo $wishlistHelper->getAddUrl($_product) ?>" class="towishlist link-wishlist"><?php echo $this->__('Add to Wishlist') ?></a>
                        </div>
                        <?php endif; ?>
                        <div class="product-item-inner">
                            <?php if ($showName): ?>
                            <strong class="product-name"><a class="product-item-link grid-pesquisa-font" href="<?= $url; ?>"><?= $name; ?></a></strong>
                            <?php endif ?>
                            <div class="ratting">
                            <i class="fas fa-star" aria-hidden="true"></i>
                            <i class="fas fa-star" aria-hidden="true"></i>
                             <i class="fas fa-star" aria-hidden="true"></i>
                            <i class="fas fa-star" aria-hidden="true"></i>
                            <i class="far fa-star" aria-hidden="true"></i>
                            </div>




                            <?php if ($showSku) : ?>
                            <div class="product-item-sku"><span class="label"><?= $this->__('SKU: ') ?></span><span class="value"><?= $_product->getData('sku') ?></span></div>
                            <?php endif ?>
                            <?= $showPrice ? $this->getPriceHtml($_product, true) : '' ?>
                            <?= ($showReview && $_product->getRatingSummary()) ? $this->getReviewsSummaryHtml($_product, 'short') : ''; ?>
                            <?php if ($showDescription):?>
                            <div class="product description product-item-description">
                                <?= $themeHelper->subString($_helper->productAttribute($_product, $_product->getShortDescription(), 'short_description'), 70) ?>
                            </div>

                            <?php endif; ?>
                            <?php
                            if ($this->getChild('name.after')) {
                                $_nameAfterChildren = $this->getChild('name.after')->getSortedChildren();
                                foreach ($_nameAfterChildren as $_nameAfterChildName) {
                                    $_nameAfterChild = $this->getChild('name.after')->getChild($_nameAfterChildName);
                                    $_nameAfterChild->setProduct($_product);
                                    echo $_nameAfterChild->toHtml();
                                }
                            }
                            ?>
                            <?php if ($showCart || $showWishlist || $showCompare) : ?>
                            <div class="actions-secondary botoes-produto">
                                <?php if(!$_product->canConfigure() && $_product->isSaleable()): ?>
                                    <button type="button" title="<?php echo $this->quoteEscape($this->__('Add to Cart')) ?>" class="button btn-cart" onclick="setLocation('<?php echo $this->getAddToCartUrl($_product) ?>')"><span><span><?php echo $this->__('Add to Cart') ?></span></span></button>
                                <?php elseif($_product->canConfigure() && $_product->isSaleable()): ?>
                                    <button type="button" title="<?php echo $this->quoteEscape($this->__('Add to Cart')) ?>" class="button btn-cart" onclick="CodazonAjaxCartPro.getConfigurableOptions('<?php echo $this->getUrl('quickviewpro/cart/view', array('id' => $_product->getId())) ?>')"><span><span><?php echo $this->__('Add to Cart') ?></span></span></button>
                                <?php elseif($_product->getStockItem() && $_product->getStockItem()->getIsInStock()): ?>
                                    <a title="<?php echo $this->quoteEscape($this->__('View Details')) ?>" class="button" href="<?php echo $_product->getProductUrl() ?>"><?php echo $this->__('View Details') ?></a>
                                <?php else : ?>
                                    <button type="button" title="<?php echo $this->quoteEscape($this->__('Out of stock')) ?>" class="button btn-cart out-of-stock disabled unavailable" disabled><span><span><?php echo $this->__('Out of stock') ?></span></span></button>
                                <?php endif ?>
                                <?php if ($showWishlist) : ?>
                                <a href="<?php echo $wishlistHelper->getAddUrl($_product) ?>" class="towishlist link-wishlist"><?php echo $this->__('Add to Wishlist') ?></a>
                                <?php endif; ?>
                                <?php if(($_compareUrl = $this->getAddToCompareUrl($_product)) && $showCompare): ?>
                                <a href="<?php echo $_compareUrl ?>" class="tocompare link-compare"><?php echo $this->__('Add to Compare') ?></a>
                                <?php endif; ?>
                            </div>
                            <?php endif; ?>
                        </div>
                    </div>
                </div>
            </div>
        </li>
        <?php endforeach ?>
    </ul>
    <div class="toolbar-bottom">
        <?php echo $this->getToolbarHtml() ?>
    </div>
</div>
<?php
// Provides a block where additional page components may be attached, primarily good for in-page JavaScript
if ($this->getChild('after')) {
    $_afterChildren = $this->getChild('after')->getSortedChildren();
    foreach ($_afterChildren as $_afterChildName) {
        $_afterChild = $this->getChild('after')->getChild($_afterChildName);
        //set product collection on after blocks
        $_afterChild->setProductCollection($_productCollection);
        echo $_afterChild->toHtml();
    }
}
?>
<?php endif ?>
<?php endif ?>

<script>

    function saveQtd(id, url){
        console.log(id, url);
        var elementId = "#qty_" + id;
        var ProdutcQtd = jQuery(elementId).val();
        var baseUrl = "<?php echo Mage::getUrl(); ?>";

        jQuery.ajax({
            method: "POST",
            dataType: "json",
            url: baseUrl + "listafavoritos/ajax/salvarQtdProdutos",
            data: { produtcQtd: ProdutcQtd, product_id: id }
        })
            .done(function( msg ) {
                console.log(msg);
                window.location = url;
            });
    }

    function abrirOpcoes(id){
        console.log("chegou aui" + id);
        var element = "#mostrar-opcoes-" + id;
        jQuery(element).show();

    }

    function fecharJanela(id){

        console.log("chegou aui" + id);
        var element = "#mostrar-opcoes-" + id;
        jQuery(element).hide();

    }

    function addProductFavoritos(id, userId, that){

        var element = "#mostrar-opcoes-" + id;
        var adicionar = "#btn-adicionar-fav-" + id;
        var remover = "#btn-remover-fav-" + id;
        var divMsg = "#msg-" + id;
        var listaSelecionada = "#select-lista-favorito-" + id;
        listaSelecionada = jQuery(listaSelecionada).val();
        var baseUrl = "<?php echo Mage::getUrl(); ?>";

        console.log(id, userId);

        jQuery.ajax({
            method: "POST",
            dataType: "json",
            url: baseUrl + "listafavoritos/ajax/cadastrarProdutosFavoritos",
            data: { produtcId: id, userId: userId, listaSelecionada: listaSelecionada }
        })
            .done(function( msg ) {
                console.log(msg);
                if(msg.ativo == 1){
                    jQuery(that).addClass("adicionado-fav");
                    console.log("add");

                    jQuery(element).hide();
                    jQuery(divMsg).show();
                    jQuery(adicionar).show();
                    jQuery(remover).hide();
                }else{
                    jQuery(divMsg).hide();
                    jQuery(adicionar).hide();
                    jQuery(remover).show();

                }
            });
    }

</script>


<style>

li.item.product.product-item.grid-pesquisa {
    transition: all 500ms ease;
    /* padding: 10px; */
    margin: 10px 10px;
        border-radius: 15px;
    transition: all 500ms ease-in-out;
    border: 1px solid #e8e8e8;
    margin-bottom: 15px;
    /* background-color: #fbfbfb; */

}
li.item.product.product-item.grid-pesquisa:hover {
    box-shadow: 0px 0px 5px 1px #bfbfbf;
}
.grid-pesquisa span.regular-price>span.price {
    font-size: 25px!important;
    color: #ecc700!important;
    font-weight: 600;
    letter-spacing: 1px;
}
button#btn-comprar {
    background-color: red;
    border-color: red;
    color: white;
    border-radius: 5px;
}
.grid-pesquisa .product-list-style-14 .button-hover-wrap .qs-button, .product-list-style-14 .button-hover-wrap .tocompare, .product-list-style-14 .button-hover-wrap .btn-cart {
    color: #fff;
    border-color: red!important;
    background: red!important;
}
a.product-item-link.grid-pesquisa-font {
    font-size: 12px;
}
.product.details.product-item-details.product-info span.value {
    display: none;
}
.actions-secondary.botoes-produto > button.button.btn-cart {
    background-color: red;
    border-color: red;
    border-radius: 5px;
    transition: all 500ms ease-out;
    color: white;
}
li.item.product.product-item.grid-pesquisa .product-item-inner {
    height: auto!important;
}
li.item.product.product-item.grid-pesquisa a.product-image.abs-img {
    padding-bottom: 100%!important;
}
a.product-item-link.grid-pesquisa-font {
    min-height: 60px!important;
    display: block;
}
.actions-secondary.botoes-produto > button:hover {
    transform: scale3d(1.3, 1.1, 1.1);
}





#btn-comprar{
    transition: all 500ms ease;
}
#btn-comprar:hover{
    background-color: #479789;
    color: white;
}
.box-quero {
    font-size: 17px;
    display: revert;
    background-color: #26bf26;
    padding: 5px;
    border-radius: 5px;
    color: white;
    letter-spacing: 4px;
    font-weight: 800;
    transition: all 500ms ease-out;
    cursor: pointer;

}
.box-info-nova:hover .box-quero.mostrar {
    display: none;
}
.box-info-nova:hover .box-quero.oculto {
    display: block;
}
.box-quero.oculto{
    display: none;
}
.product.details.product-item-details.product-info {
    min-height: 200px!important;
}
.box-info-nova {
    height: 40px;
}
.cart-qty.home {
    width: 100%;
    display: flex;
    justify-content: center;
    margin: 5px 0px;
    border: none;
}

.cart-qty.home input#qty{
    height: 30px;
}
.cart-qty.home button.increase, .cart-qty.home button.decrease {
    padding: 0px 9px;
    background-color: white;
    border-color: red;
    color: red;
    /* font-size: 9px; */
    font-size: 20px;
    border-radius: 50%;
}
.cart-qty.home input#qty{
    border: none;
    font-size: 20px;
    width: 15%;
    color: black;
    font-weight: 500;
}
body.cms-index-index.cms-codazon-home-page.page-main-full.cdz-fullwidth-fix-left .product-item-inner > strong.product-name {
    height: 50px;
}
.home a.product-image.abs-img{
    padding-bottom: 100%!important;
}
.btn-favoritos, button.adicionado-fav{
    border:none!important;
}
i.fas.fa-heart, i.far.fa-heart {
    font-size: 20px;
    color: red;
}
.box-wish-list {
    position: fixed;
    /* top: 4%; */
    /* display: grid; */
    background-color: white;
    z-index: 999;
    /* left: -52%; */
    margin-left: auto;
    margin-right: auto;
    left: 13%;
    /* text-align: center; */
    /* width: 287px; */
    color: black;
    box-shadow: 0px 0px 10px 1px grey;
    padding: 1%;
    border-radius: 10px;
    text-align: center;
}
.class_select_wish_list select.select-lista-favorito {
    border: none;
    box-shadow: 0px 0px 10px 1px #cecece;
    border-radius: 10px;
    margin: 10px 0px;
    padding: 0px 10px;
}
button.btn-add-prodcut-list {
    background-color: #ff0014;
    border-color: #ff0014;
    color: white;
    font-weight: 600;
    border-radius: 10px;
}
</style>




