<?php
/**
 * Copyright © 2017 Codazon, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<?php
$customerSession = Mage::getSingleton('customer/session');
$_productCollection = $this->getProductCollection();
$_helper = $this->helper('catalog/output');
$labelHelper = $this->getLabelHelper();
$quickShopHelper = $this->helper('quickviewpro');
$imageHelper = $this->helper('catalog/image');
$wishlistHelper = $this->helper('wishlist');
$showSlider = $this->getData('show_slider');

$width = $this->getData('thumb_width');
$height = $this->getData('thumb_height');
$paddingBottom = $height*100/$width;

$showDescription = $this->isShow('description');
$showSku = $this->isShow('sku');
$showWishlist = $this->isShow('wishlist') && $wishlistHelper->isAllow();
$showCompare = $this->isShow('compare');
$showCart = $this->isShow('addtocart');
$showQuickShop = $this->isShow('quickshop');
$showLabel = $this->isShow('label');
$showThumb = $this->isShow('thumb');
$showName = $this->isShow('name');
$showReview = $this->isShow('review');
$showPrice = $this->isShow('price');

$totalRows = (int)$this->getData('total_rows');
$totalCols = (int)$this->getData('total_cols');
$uniqid = uniqid();
$widget = array(
    'codazon.slider' => array('sliderConfig' => $this->getSliderData())
);

?>

<?php if($_count = $_productCollection->count()): ?>
<div class="grid-style-13 products">
<div class="products list items product-items<?= $showSlider?' owl-carousel':'' ?>" <?php if ($showSlider) : ?>data-cdzwidget='<?= json_encode($widget) ?>'<?php endif ?>>
<?php $i = 0; foreach ($_productCollection as $_product): ?>
<?php
$name = $this->stripTags($_product->getName(), null, true);
$url = $_product->getProductUrl();
?>
    <?php if ($i%$totalRows == 0) : ?>
    <div class="item-group">
    <?php endif ?>
	<div class="discount" style="background-color: rgb(108 201 71);align-items: center;text-align: center;padding: 10px;color: white;font-weight: bold;-webkit-box-align: center;-webkit-box-pack: center;justify-content: center;">ofertas do dia</div>
        <div class="item product product-item">
            <div class="product-item-info home">
                <?php if($customerSession->isLoggedIn()) {
                        $is_favorite = Mage::getModel("cistecnologia_listafavoritos/favoritos")->checkFavorite($_product, $customerSession->getId());
                        $listaFavoritos = Mage::getModel("cistecnologia_listafavoritos/favoritos")->getListaFavoritosCollection($customerSession->getId());
                    ?>
                    <div class="wishlist">
                            <button id="btn-adicionar-fav-<?php echo $_product->getId(); ?>" class="adicionado-fav" onclick="addProductFavoritos(<?php echo $_product->getId(); ?>, <?php echo $customerSession->getId(); ?>, this)" <?php echo ($is_favorite)? "" : "style='display: none'" ;?>>
                            <i class="fas fa-heart"></i></button>
                            
                            <button id="btn-remover-fav-<?php echo $_product->getId(); ?>" class="remove-fav btn-favoritos" onclick="abrirOpcoes(<?php echo $_product->getId(); ?>)" <?php echo ($is_favorite)? "style='display: none'" : "" ;?>>
                           
                           
                            <i class="far fa-heart"></i>

                        </button>

                        <!-- <div id="msg-<?php echo $_product->getId(); ?>" style="display: none">Produto adicionado as seus favoritos!</div> -->
                        <div class="box-wish-list" id="mostrar-opcoes-<?php echo $_product->getId(); ?>" style="display: none">
                            <div>
                                <div class="title_wish_list">Selecione a Lista para adicionar o seu favorito</div>
                                <div class="class_select_wish_list">
                                    <select id="select-lista-favorito" name="select-lista-favorito">
                                        <option value="0">Selecione</option>
                                        <?php foreach ($listaFavoritos as $lista){?>
                                            <option value="<?php echo $lista["lista_favoritos_id"]; ?>"><?php echo $lista["lista_favoritos_nome"]; ?></option>
                                        <?php } ?>     
                                    </select>
                                </div>
                            </div>
                            <div>
                                <button class="btn-add-prodcut-list" onclick="addProductFavoritos(<?php echo $_product->getId(); ?>, <?php echo $customerSession->getId(); ?>, this)">Adicionar</button>
                            </div>
                        </div>
                    </div>
                <?php } ?>
                <div class="product-item-top">
                    <a href="<?= $url ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" class="product-image abs-img" style="padding-bottom: <?php echo $paddingBottom ?>%">
                        <img class="product-image-photo main-img" src="<?= $imageHelper->init($_product, 'small_image')->resize($width, $height); ?>" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" />
                        <img class="product-image-photo hovered-img" src="<?= $imageHelper->init($_product, 'thumbnail')->resize($width, $height); ?>" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'thumbnail'), null, true) ?>" />
                    </a>
                    <?= $showLabel?$labelHelper->showLabel($_product):''; ?>
                    <?php if ($showCart || $showCompare || $showQuickShop) : ?>
                    <div class="button-hover-wrap hidden-xs">
                        <div class="overlay-bg"></div>
                        <div class="button-panel">
                        <?php if ($showCart) : ?>
                        <?php if ($_product->isSaleable()) : ?>
							<!-- <button type="button" id="btn-comprar" title="<?php echo $this->quoteEscape($this->__('Add to Cart')) ?>" onclick="setLocation('<?= $url ?>')"  class="button">Comprar</button> -->
                            <!-- <button type="button" title="<?php echo $this->quoteEscape($this->__('Add to Cart')) ?>" class="button btn-cart" onclick="setLocation('<?php echo $this->getAddToCartUrl($_product) ?>')"><span>Comprar</span></button> -->
						<?php else : ?>
							<button type="button" title="<?php echo $this->quoteEscape($this->__('Out of stock')) ?>" class="button btn-cart out-of-stock disabled unavailable"disabled><span><span><?php echo $this->__('Out of stock') ?></span></span></button>
						<?php endif ?>
                        <?php endif ?>
                        <!-- <?= $showQuickShop?$quickShopHelper->getQuickShopButton($_product):''; ?> -->
                        <?php if(($_compareUrl=$this->getAddToCompareUrl($_product)) && $showCompare): ?>
                        
                        <?php endif; ?>
                        </div>
                    </div>
                    <?php endif; ?>
                </div>
                <div class="product details product-item-details product-info">
                    <div class="detail-items-wrap">
                        <?php if ($showWishlist) : ?>
                        <div class="product-item-header">
                            <!-- <a href="#" class="product-item-brand">Clothing</a>
                            <a href="<?php echo $wishlistHelper->getAddUrl($_product) ?>" class="towishlist link-wishlist"><?php echo $this->__('Add to Wishlist') ?></a> -->
                        </div>
                        <?php endif; ?>
                        
                        <div class="product-item-inner">
                            <?php if ($showName): ?>
                            <strong class="product-name">
                                <a class="product-item-link" href="<?= $_product->getProductUrl(); ?>">
                                    <?= $name; ?>
                                </a>
                            </strong>
                            <?php endif ?>
                            
                            <?php if ($showSku) : ?>
                            <div class="product-item-sku"><span class="label"><?= __('SKU: ') ?></span><span class="value"><?= $_product->getData('sku') ?></span></div>
                            <?php endif ?>
                                          <!-- <div class="ratting">
                            <i class="fas fa-star"></i>
                            <i class="fas fa-star"></i>
                             <i class="fas fa-star"></i>
                            <i class="fas fa-star"></i>
                            <i class="far fa-star"></i> 
                            </div> -->

                            <?= $showReview ? $this->getReviewsSummaryHtml($_product, 'short') : ''; ?>
                            <?= $showPrice ? $this->getPriceHtml($_product, true, $uniqid) : '' ?>
                            <?php if ($showDescription):?>
                            <div class="product description product-item-description">
                                <?= $this->subString($_helper->productAttribute($_product, $_product->getShortDescription(), 'short_description'), 70) ?>
                            </div>
                            <?php endif; ?>
                            
              
                            <div class="actions-secondary visible-xs">
                                <?php if ($_product->isSaleable()) : ?>
                                   <button type="button" id="btn-comprar" title="<?php echo $this->quoteEscape($this->__('Add to Cart')) ?>" onclick="setLocation('<?= $url ?>')"  class="button">Comprar</button>
                                                                   <?= $quickShopHelper->getQuickShopButton($_product); ?>

                                <?php else : ?>
                                    <button type="button" title="<?php echo $this->quoteEscape($this->__('Out of stock')) ?>" class="button btn-cart out-of-stock disabled unavailable"disabled><span><span><?php echo $this->__('Out of stock') ?></span></span></button>
                                <?php endif ?>
                                <?php if ($wishlistHelper->isAllow() && $showWishlist) : ?>
                                <a href="<?php echo $wishlistHelper->getAddUrl($_product) ?>" class="towishlist link-wishlist"><?php echo $this->__('Add to Wishlist') ?></a>
                                <?php endif; ?>
                                <?php if (($_compareUrl=$this->getAddToCompareUrl($_product)) && $showCompare) : ?>
                                <a href="<?php echo $_compareUrl ?>" class="tocompare link-compare"><?php echo $this->__('Add to Compare') ?></a>
                                <?php endif; ?>
                            </div>

                            <!-- <div class="field qty qty-wrapper">
            <label for="qty"><?php echo $this->__('Qty:') ?></label>
            <div class="control">
               
            </div>
        </div> -->

        <div class="cart-qty home">
                    <div class="qty-ctl">
                        <button title="<?= $this->__('Decrease') ?>" type="button" data-role="change_cart_qty" class="decrease" data-qty="-1" class="decrease">-</button>
                    </div>
                    <input type="text" pattern="\d*(\.\d+)?" name="qty" id="qty_<?php echo $_product->getId() ;?>" maxlength="12" value="<?php echo $this->getProductDefaultQty() * 1 ?>" title="<?php echo Mage::helper('core')->quoteEscape($this->__('Qty')) ?>" class="input-text qty" />
                    <div class="qty-ctl">
                        <button title="<?= $this->__('Increase') ?>" type="button" data-role="change_cart_qty" data-qty="1" class="increase">+</button>
                    </div>
                </div>
                             <div class="box-info-nova">

                                 <div onclick="saveQtd(<?php echo $_product->getId(); ?>, '<?php echo $url; ?>');" class="box-quero mostrar">EU QUERO!</div>
                                 <div onclick="saveQtd(<?php echo $_product->getId(); ?>, '<?php echo $url; ?>');" class="box-quero oculto">COMPRE JÁ!</div>

                             </div>
                             
                            
                        </div>
                        
                    </div>
                </div>
            </div>
        </div>
    <?php if ( ($i%$totalRows == ($totalRows -1 )) || ($i == ($_count - 1)) ) : ?>
    </div>
    <?php endif ?>
<?php $i++; endforeach ?>
</div>
</div>
<?php else : ?>
<div class="note-msg"><div><?php echo $this->__('There are no products matching the selection.') ?></div></div>
<?php endif; ?>


<script>

    function saveQtd(id, url){
        console.log(id, url);
        var elementId = "#qty_" + id;
        var ProdutcQtd = jQuery(elementId).val();
        jQuery.ajax({
            method: "POST",
            dataType: "json",
            url: "listafavoritos/ajax/salvarQtdProdutos",
            data: { produtcQtd: ProdutcQtd, product_id: id }
        })
            .done(function( msg ) {
                console.log(msg);
                window.location = url;
            });
    }

    function abrirOpcoes(id){
        console.log("chegou aui" + id);
        var element = "#mostrar-opcoes-" + id;
        jQuery(element).show();

    }

    function addProductFavoritos(id, userId, that){

        var element = "#mostrar-opcoes-" + id;
        var adicionar = "#btn-adicionar-fav-" + id;
        var remover = "#btn-remover-fav-" + id;
        var divMsg = "#msg-" + id;

        console.log(id, userId);

        jQuery.ajax({
            method: "POST",
            dataType: "json",
            url: "listafavoritos/ajax/cadastrarProdutosFavoritos",
            data: { produtcId: id, userId: userId }
        })
            .done(function( msg ) {
                console.log(msg);
                if(msg.ativo == 1){
                    jQuery(that).addClass("adicionado-fav");
                    console.log("add");

                    jQuery(element).hide();
                    jQuery(divMsg).show();
                    jQuery(adicionar).show();
                    jQuery(remover).hide();
                }else{
                    jQuery(divMsg).hide();
                    jQuery(adicionar).hide();
                    jQuery(remover).show();

                }
            });
    }

</script>


<style>
#btn-comprar{
    transition: all 500ms ease;
}
#btn-comprar:hover{
    background-color: #479789;
    color: white;
}
.box-quero {
    font-size: 17px;
    display: revert;
    background-color: #26bf26;
    padding: 5px;
    border-radius: 5px;
    color: white;
    letter-spacing: 4px;
    font-weight: 800;
    transition: all 500ms ease-out;
    cursor: pointer;

}
.box-info-nova:hover .box-quero.mostrar {
    display: none;
}
.box-info-nova:hover .box-quero.oculto {
    display: block;
}
.box-quero.oculto{
    display: none;
}
.product.details.product-item-details.product-info {
    min-height: 200px!important;
}
.box-info-nova {
    height: 40px;
}
.cart-qty.home {
    width: 100%;
    display: flex;
    justify-content: center;
    margin: 5px 0px;
    border: none;
}

.cart-qty.home input#qty{
    height: 30px;
}
.cart-qty.home button.increase, .cart-qty.home button.decrease {
    padding: 0px 9px;
    background-color: white;
    border-color: red;
    color: red;
    /* font-size: 9px; */
    font-size: 20px;
    border-radius: 50%;
}
.cart-qty.home input#qty{
    border: none;
    font-size: 20px;
    width: 15%;
    color: black;
    font-weight: 500;
}
body.cms-index-index.cms-codazon-home-page.page-main-full.cdz-fullwidth-fix-left .product-item-inner > strong.product-name {
    height: 50px;
}
.home a.product-image.abs-img{
    padding-bottom: 100%!important;
}
.btn-favoritos, button.adicionado-fav{
    border:none!important;
}
i.fas.fa-heart, i.far.fa-heart {
    font-size: 20px;
    color: red;
}
.box-wish-list {
    position: fixed;
    /* top: 4%; */
    /* display: grid; */
    background-color: white;
    z-index: 999;
    /* left: -52%; */
    margin-left: auto;
    margin-right: auto;
    left: 13%;
    /* text-align: center; */
    /* width: 287px; */
    color: black;
    box-shadow: 0px 0px 10px 1px grey;
    padding: 1%;
    border-radius: 10px;
    text-align: center;
}
.class_select_wish_list select#select-lista-favorito {
    border: none;
    box-shadow: 0px 0px 10px 1px #cecece;
    border-radius: 10px;
    margin: 10px 0px;
    padding: 0px 10px;
}
button.btn-add-prodcut-list {
    background-color: #ff0014;
    border-color: #ff0014;
    color: white;
    font-weight: 600;
    border-radius: 10px;
}
</style>