<div class="main-col-inner">
    <div id="messages"></div>
    <script type="text/javascript">
        if (typeof jQuery == 'undefined') {
            document.write(unescape("%3Cscript src='http://ajax.googleapis.com/ajax/libs/jquery/1.10.0/jquery.min.js' type='text/javascript'%3E%3C/script%3E"));
        }
    </script><script src="http://ajax.googleapis.com/ajax/libs/jquery/1.10.0/jquery.min.js" type="text/javascript"></script>
    <script type="text/javascript">
        $wk_jq=jQuery.noConflict();
        var acceptedImageType = ["jpg", "jpeg", "gif", "png"];
        $wk_jq("#filename").change(function(){
            var imageName = $wk_jq(this).val();
            var result = imageName.split(".");
            var length = result.length;
            if(acceptedImageType.indexOf(result[length-1])!=-1) {
            } else {
                $wk_jq("#filename").val("");
                alert("Invalid Image Format");
            }
        });
        $wk_jq("#banner").change(function(){
            var imageName = $wk_jq(this).val();
            var result = imageName.split(".");
            var length = result.length;
            if(acceptedImageType.indexOf(result[length-1])!=-1) {
            } else {
                $wk_jq("#filename").val("");
                alert("Invalid Image Format");
            }
        });
    </script><div class="content-header">
        <h3 class="icon-head head-adminhtml-postcode">Cadastro de Produtos</h3>
        <p class="form-buttons">
            <button id="id_bc37f1b6bfaa38063b6f9119d8c311a4" title="Voltar" type="button" class="scalable back" onclick="setLocation('http://localhost:8888/camellia/index.php/postcodeadmin/adminhtml_postcode/index/key/f2e89300a90d68f85dd54ce5411646e5/')" style="">
                <span>
                    <span>
                        <span>Voltar</span>
                    </span>
                </span>
            </button>
            <button id="id_df3db14c4b06b68b9bbab1880d3673eb" title="Save Item" type="button" class="scalable save" onclick="saveAndContinueEdit();" style="">
                <span><span><span>Salvar</span></span></span>
            </button>
        </p>
    </div>
    <div class="entry-edit">
        <form id="edit_form" action="<?php echo Mage::getBaseUrl('web')?>" method="post" enctype="multipart/form-data">
            <div>
                <input name="form_key" type="hidden" value="<?php echo Mage::getSingleton('core/session')->getFormKey() ?>">
            </div>
            <div id="postcode_tabs_form_section_content" style="">
                <div class="entry-edit">
                    <div class="entry-edit-head">
                        <h4 class="icon-head head-edit-form fieldset-legend">Adicionar Itens</h4>
                        <div class="form-buttons"></div>
                    </div>
                    <div class="fieldset " id="postcode_form">
                        <div class="hor-scroll">
                            <table cellspacing="0" class="form-list">
                                <tbody>
                                <tr>
                                    <td class="label"><label for="title">Entrada <span class="required">*</span></label></td>
                                    <td class="value">
                                        <input id="entrada_opc1" name="entrada_opc1" value="" class="required-entry input-text required-entry" type="text">
                                    </td>
                                    <td class="value">
                                        <input id="entrada_opc2" name="entrada_opc2" value="" class="required-entry input-text required-entry" type="text">
                                    </td>
                                </tr>
                                <tr>
                                    <td class="label"><label for="postcode_from">Principal<span class="required">*</span></label></td>
                                    <td class="value">
                                        <input id="principal_opc1" name="principal_opc1" value="" class="required-entry input-text required-entry" type="text">
                                    </td>
                                    <td class="value">
                                        <input id="principal_opc2" name="principal_opc2" value="" class="required-entry input-text required-entry" type="text">
                                    </td>
                                </tr>
                                <tr>
                                    <td class="label"><label for="postcode_to">Sobremesa <span class="required">*</span></label></td>
                                    <td class="value">
                                        <input id="sobremesa_opc1" name="sobremesa_opc1" value="" class="required-entry input-text required-entry" type="text">
                                    </td>
                                    <td class="value">
                                        <input id="sobremesa_opc2" name="sobremesa_opc2" value="" class="required-entry input-text required-entry" type="text">
                                    </td>
                                </tr>
                                <tr>
                                    <td class="label"><label for="status">Doação Delivery Solidário?</label></td>
                                    <td class="value">
                                        <select id="doacao" name="doacao" class="select">
                                            <option value="true">Sim</option>
                                            <option value="false">Não</option>
                                        </select>
                                    </td>
                                </tr>
                                <tr>
                                    <td class="label"><label for="status">Status</label></td>
                                    <td class="value">
                                        <select id="status" name="status" class=" select">
                                            <option value="1">Habilitado</option>
                                            <option value="2">Desativado</option>
                                        </select>            </td>
                                </tr>
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </form>
    </div>
    <script type="text/javascript">
        editForm = new varienForm('edit_form', '');
    </script>
    <script type="text/javascript">
        function toggleEditor() {
            if (tinyMCE.getInstanceById('postcode_content') == null)
                tinyMCE.execCommand('mceAddControl', false, 'postcode_content');
            else
                tinyMCE.execCommand('mceRemoveControl', false, 'postcode_content');
        }

        function saveAndContinueEdit(){

            console.log($('edit_form').action+'tree/adminhtml_tree/saveFuture');

            /*var baseUrl = "<?php echo Mage::getBaseUrl('web')?>";
            var urlParentInsta = '<?php echo Mage::getModel('adminhtml/url')->getUrl('tree/adminhtml_tree/getParentsByInsta/'); ?>';
            var url = 'tree/adminhtml_tree/saveFuture';

            jQuery('#upload').on('click', function() {

                var file_data = jQuery('#arquivo').prop('files');
                var imput_data = jQuery('#form_key').val();
                var form_data = new FormData();
                form_data.append('file', file_data);
                form_data.append('form_key', imput_data);
                console.log(form_data);
                jQuery.ajax({
                    url: baseUrl+url,
                    contentType: 'multipart/form-data',
                    cache: false,
                    processData: false,
                    data: form_data,
                    type: 'post',
                    success: function(response){
                        console.log(response);
                    }
                });
            });*/

            editForm.submit($('edit_form').action+'tree/adminhtml_tree/saveFuture/');
        }
    </script>                        </div>